name: Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  go:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: asdf_install
        uses: asdf-vm/actions/install@v1

      - name: Test
        run: |
          export PATH=${PATH}:`go env GOPATH`/bin
          go install github.com/magefile/mage
          mage setuptest
          mage test
          mage gomodtidy

  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Attempt build the Docker image
        run: docker build .
